import { createContext, useContext, useState, useEffect } from 'react';

const AppContext = createContext();

// Tarjimalar
const translations = {
  uz: {
    // Sidebar
    home: 'Asosiy',
    teachers: "O'qituvchilar",
    classes: 'Guruhlar',
    students: 'Talabalar',
    gifts: "Sovg'alar",
    management: 'Boshqarish',
    subscription: 'Obuna',
    subscriptionExpired: 'Obunangiz tugagan',
    renewSubscription: 'Obunani yangilash',
    // Header
    search: 'Qidirish...',
    logout: 'Chiqish',
    // Dashboard
    activeStudents: 'Faol talabalar',
    groups: 'Guruhlar',
    monthlyPayments: "Joriy oy to'lovlar",
    debtors: 'Qarzdorlar',
    frozen: 'Muzlatiganlar',
    archived: 'Arxivdagilar',
    monthlyPaymentsTitle: "Joriy oy uchun to'lovlar",
    annualProfit: 'Yillik Foyda',
    schedule: 'Dars jadvali',
    // Common
    save: 'Saqlash',
    cancel: 'Bekor qilish',
    add: "Qo'shish",
    edit: 'Tahrirlash',
    delete: "O'chirish",
    loading: 'Yuklanmoqda...',
    noData: "Ma'lumot yo'q",
    requiredFields: "Iltimos, barcha majburiy maydonlarni kiriting!",
    // Classes
    addGroup: "Guruh qo'shish",
    editGroup: "Guruhni tahrirlash",
    groupName: 'Guruh nomi',
    course: 'Kurs',
    room: 'Xona',
    lessonDays: 'Dars kunlari',
    lessonTime: 'Dars vaqti',
    startDate: 'Boshlanish sanasi',
    active: 'Faol',
    archive: 'Arxiv',
    // Teachers
    addTeacher: "O'qituvchi qo'shish",
    // Students
    addStudent: "Talaba qo'shish",
    // GroupDetail tabs
    info: "Ma'lumotlar",
    lessons: 'Guruh darsliklari',
    attendance: 'Akademik davomati',
    homework: 'Uyga vazifa',
    videos: 'Videolar',
    exams: 'Imtihonlar',
    journal: 'Jurnal',
    addHomework: "Qo'shish",
    newExam: 'Yangi imtihon',
    statistics: 'Statistika',
    langName: "O'zbekcha",
    // Dashboard
    noDataAvailable: "Ma'lumotlar mavjud emas",
    // Classes
    groupsTab: 'Guruhlar',
    archiveTab: 'Arxiv',
    editGroupDesc: "Guruh ma'lumotlarini tahrirlash uchun quyidagilarni o'zgartiring.",
    createGroupDesc: "Yangi guruh yaratish uchun quyidagi ma'lumotlarni kiriting.",
    selectCourse: 'Kursni tanlang',
    selectRoom: 'Xonani tanlang',
    addStudent: 'Talaba qo\'shish',
    selectStudents: 'Bitta yoki bir nechta talabani tanlang',
    searchStudent: 'Talaba qidirish...',
    noStudentsFound: 'Talabalar topilmadi',
    addTeacher: "O'qituvchi qo'shish",
    selectTeachers: 'Bitta yoki bir nechta o\'qituvchini tanlang',
    searchTeacher: "O'qituvchi qidirish...",
    noTeachersFound: "O'qituvchilar topilmadi",
    roomBusy: 'Bu xona tanlangan kun va vaqtda band! Boshqa xona, vaqt yoki kun tanlang.',
    serverError: 'Server bilan ulanishda xatolik!',
    // Students
    editStudentDesc: 'Bu yerda siz yangi talaba qo\'shishingiz mumkin.',
    phoneNumber: 'Telefon raqam',
    email: 'Mail',
    enterEmail: 'Elektron pochtani kiriting',
    studentName: 'Talaba FIO',
    enterInfo: "Ma'lumotni kiriting",
    birthDate: "Tug'ilgan sanasi",
    address: 'Manzil',
    enterAddress: 'Manzilni kiriting',
    password: 'Parol',
    enterPassword: 'Parolni kiriting',
    photo: 'Surati',
    clickUpload: 'Click to upload',
    uploadDesc: 'JPG or PNG (max. 2 MB)',
    deleteStudent: "Talabani o'chirish",
    deleteConfirm: 'ni rostdan ham o\'chirishni hohlaysizmi?',
    deleteWarning: "O'chirilgan ma'lumot arxivga o'tkaziladi.",
    yesDelete: 'Ha, o\'chirish',
    attachGroups: 'Guruhlarga biriktirish',
    searchGroup: 'Guruh qidirish...',
    groupsLoading: 'Guruhlar yuklanmoqda...',
    noGroupsAvailable: 'Guruhlar mavjud emas yoki yuklanmadi',
    noGroupsFound: 'Guruhlar topilmadi',
    phoneExists: 'Bu telefon raqam yoki email allaqachon mavjud!',
    serverErrorOccurred: 'Server xatosi yuz berdi',
    studentsPageDesc: "Ushbu sahifada siz Talabalar ro'yxatini va ularning ma'lumotlarini topasiz. Har bir Talaba ismi, fanlari va aloqa ma'lumotlari keltirilgan.",
  },
  ru: {
    home: 'Главная',
    teachers: 'Учителя',
    classes: 'Группы',
    students: 'Студенты',
    gifts: 'Подарки',
    management: 'Управление',
    subscription: 'Подписка',
    subscriptionExpired: 'Подписка истекла',
    renewSubscription: 'Обновить подписку',
    search: 'Поиск...',
    logout: 'Выйти',
    activeStudents: 'Активные студенты',
    groups: 'Группы',
    monthlyPayments: 'Оплаты за месяц',
    debtors: 'Должники',
    frozen: 'Замороженные',
    archived: 'В архиве',
    monthlyPaymentsTitle: 'Оплаты за текущий месяц',
    annualProfit: 'Годовая прибыль',
    schedule: 'Расписание',
    save: 'Сохранить',
    cancel: 'Отмена',
    add: 'Добавить',
    edit: 'Изменить',
    delete: 'Удалить',
    loading: 'Загрузка...',
    noData: 'Нет данных',
    requiredFields: 'Пожалуйста, заполните все обязательные поля!',
    addGroup: 'Добавить группу',
    editGroup: 'Редактировать группу',
    groupName: 'Название группы',
    course: 'Курс',
    room: 'Комната',
    lessonDays: 'Дни занятий',
    lessonTime: 'Время занятий',
    startDate: 'Дата начала',
    active: 'Активный',
    archive: 'Архив',
    addTeacher: 'Добавить учителя',
    addStudent: 'Добавить студента',
    info: 'Информация',
    lessons: 'Уроки группы',
    attendance: 'Академическая посещаемость',
    homework: 'Домашнее задание',
    videos: 'Видео',
    exams: 'Экзамены',
    journal: 'Журнал',
    addHomework: 'Добавить',
    newExam: 'Новый экзамен',
    statistics: 'Статистика',
    langName: 'Русский',
    // Dashboard
    noDataAvailable: 'Нет данных',
    // Classes
    groupsTab: 'Группы',
    archiveTab: 'Архив',
    editGroupDesc: 'Отредактируйте информацию о группе ниже.',
    createGroupDesc: 'Введите информацию ниже, чтобы создать новую группу.',
    selectCourse: 'Выберите курс',
    selectRoom: 'Выберите комнату',
    addStudent: 'Добавить студента',
    selectStudents: 'Выберите одного или несколько студентов',
    searchStudent: 'Поиск студента...',
    noStudentsFound: 'Студенты не найдены',
    addTeacher: 'Добавить учителя',
    selectTeachers: 'Выберите одного или несколько учителей',
    searchTeacher: 'Поиск учителя...',
    noTeachersFound: 'Учителя не найдены',
    roomBusy: 'Эта комната занята в выбранное время! Выберите другую комнату, время или день.',
    serverError: 'Ошибка соединения с сервером!',
    // Students
    editStudentDesc: 'Здесь вы можете добавить нового студента.',
    phoneNumber: 'Номер телефона',
    email: 'Email',
    enterEmail: 'Введите адрес электронной почты',
    studentName: 'Имя студента',
    enterInfo: 'Введите информацию',
    birthDate: 'Дата рождения',
    address: 'Адрес',
    enterAddress: 'Введите адрес',
    password: 'Пароль',
    enterPassword: 'Введите пароль',
    photo: 'Фото',
    clickUpload: 'Нажмите для загрузки',
    uploadDesc: 'JPG или PNG (макс. 2 МБ)',
    deleteStudent: 'Удалить студента',
    deleteConfirm: 'Вы действительно хотите удалить',
    deleteWarning: 'Удаленные данные будут архивированы.',
    yesDelete: 'Да, удалить',
    attachGroups: 'Прикрепить к группам',
    searchGroup: 'Поиск группы...',
    groupsLoading: 'Группы загружаются...',
    noGroupsAvailable: 'Группы недоступны или не загружены',
    noGroupsFound: 'Группы не найдены',
    phoneExists: 'Этот номер телефона или email уже существует!',
    serverErrorOccurred: 'Произошла ошибка сервера',
    studentsPageDesc: 'На этой странице вы можете найти список студентов и их информацию. Для каждого студента указаны имя, предметы и контактная информация.',
  },
  en: {
    home: 'Home',
    teachers: 'Teachers',
    classes: 'Groups',
    students: 'Students',
    gifts: 'Gifts',
    management: 'Management',
    subscription: 'Subscription',
    subscriptionExpired: 'Subscription expired',
    renewSubscription: 'Renew subscription',
    search: 'Search...',
    logout: 'Logout',
    activeStudents: 'Active students',
    groups: 'Groups',
    monthlyPayments: 'Monthly payments',
    debtors: 'Debtors',
    frozen: 'Frozen',
    archived: 'Archived',
    monthlyPaymentsTitle: 'Current month payments',
    annualProfit: 'Annual Profit',
    schedule: 'Schedule',
    save: 'Save',
    cancel: 'Cancel',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    loading: 'Loading...',
    noData: 'No data',
    requiredFields: 'Please fill in all required fields!',
    addGroup: 'Add group',
    editGroup: 'Edit group',
    groupName: 'Group name',
    course: 'Course',
    room: 'Room',
    lessonDays: 'Lesson days',
    lessonTime: 'Lesson time',
    startDate: 'Start date',
    active: 'Active',
    archive: 'Archive',
    addTeacher: 'Add teacher',
    addStudent: 'Add student',
    info: 'Info',
    lessons: 'Group lessons',
    attendance: 'Academic attendance',
    homework: 'Homework',
    videos: 'Videos',
    exams: 'Exams',
    journal: 'Journal',
    addHomework: 'Add',
    newExam: 'New exam',
    statistics: 'Statistics',
    langName: 'English',
    // Dashboard
    noDataAvailable: 'No data available',
    // Classes
    groupsTab: 'Groups',
    archiveTab: 'Archive',
    editGroupDesc: 'Edit the group information below.',
    createGroupDesc: 'Enter the information below to create a new group.',
    selectCourse: 'Select course',
    selectRoom: 'Select room',
    addStudent: 'Add student',
    selectStudents: 'Select one or more students',
    searchStudent: 'Search student...',
    noStudentsFound: 'No students found',
    addTeacher: 'Add teacher',
    selectTeachers: 'Select one or more teachers',
    searchTeacher: 'Search teacher...',
    noTeachersFound: 'No teachers found',
    roomBusy: 'This room is busy at the selected time! Choose another room, time, or day.',
    serverError: 'Server connection error!',
    // Students
    editStudentDesc: 'Here you can add a new student.',
    phoneNumber: 'Phone number',
    email: 'Email',
    enterEmail: 'Enter email address',
    studentName: 'Student name',
    enterInfo: 'Enter information',
    birthDate: 'Birth date',
    address: 'Address',
    enterAddress: 'Enter address',
    password: 'Password',
    enterPassword: 'Enter password',
    photo: 'Photo',
    clickUpload: 'Click to upload',
    uploadDesc: 'JPG or PNG (max. 2 MB)',
    deleteStudent: 'Delete student',
    deleteConfirm: 'Are you sure you want to delete',
    deleteWarning: 'Deleted data will be archived.',
    yesDelete: 'Yes, delete',
    attachGroups: 'Attach to groups',
    searchGroup: 'Search group...',
    groupsLoading: 'Groups loading...',
    noGroupsAvailable: 'No groups available or not loaded',
    noGroupsFound: 'No groups found',
    phoneExists: 'This phone number or email already exists!',
    serverErrorOccurred: 'Server error occurred',
    studentsPageDesc: 'On this page you can find the list of Students and their information. Each Student name, subjects and contact information are listed.',
  },
};

export const AppProvider = ({ children }) => {
  const [darkMode, setDarkMode] = useState(() => {
    return localStorage.getItem('darkMode') === 'true';
  });
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('lang') || 'uz';
  });

  // Dark mode ni HTML ga apply qilish
  useEffect(() => {
    if (darkMode) {
      document.documentElement.classList.add('dark');
      document.documentElement.style.colorScheme = 'dark';
    } else {
      document.documentElement.classList.remove('dark');
      document.documentElement.style.colorScheme = 'light';
    }
    localStorage.setItem('darkMode', darkMode);
  }, [darkMode]);

  useEffect(() => {
    localStorage.setItem('lang', lang);
  }, [lang]);

  const toggleDarkMode = () => setDarkMode(prev => !prev);

  const t = (key) => translations[lang]?.[key] || translations.uz[key] || key;

  return (
    <AppContext.Provider value={{ darkMode, toggleDarkMode, lang, setLang, t, translations }}>
      {children}
    </AppContext.Provider>
  );
};

export const useApp = () => useContext(AppContext);
